name: math_mate
description: A simple calculator app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  simple_expressions:
    git:
      url: https://github.com/kartikasw/simple_expressions.git

  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^1.1.6
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  sqflite: ^2.2.6
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  background_color_ios: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/